"""Initial creation of db tables.

Revision ID: 6f9b6675131f
Revises: 
Create Date: 2026-04-21 13:20:27.834651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9b6675131f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=False),
    sa.Column('nfl_team', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_external_ref'), 'players', ['external_ref'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('leagues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('commissioner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commissioner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_slug'), 'leagues', ['slug'], unique=True)
    op.create_table('league_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'COMMISSIONER', name='league_role', native_enum=False, length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_league_member')
    )
    op.create_index(op.f('ix_league_members_league_id'), 'league_members', ['league_id'], unique=False)
    op.create_index(op.f('ix_league_members_user_id'), 'league_members', ['user_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('draft_position', sa.Integer(), nullable=True),
    sa.Column('faab_budget_minor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'user_id', name='uq_team_league_owner')
    )
    op.create_index(op.f('ix_teams_league_id'), 'teams', ['league_id'], unique=False)
    op.create_index(op.f('ix_teams_user_id'), 'teams', ['user_id'], unique=False)
    op.create_table('draft_queue_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uq_draft_queue_team_player')
    )
    op.create_index(op.f('ix_draft_queue_entries_player_id'), 'draft_queue_entries', ['player_id'], unique=False)
    op.create_index(op.f('ix_draft_queue_entries_team_id'), 'draft_queue_entries', ['team_id'], unique=False)
    op.create_table('roster_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('is_keeper', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uq_roster_team_player')
    )
    op.create_index(op.f('ix_roster_entries_player_id'), 'roster_entries', ['player_id'], unique=False)
    op.create_index(op.f('ix_roster_entries_team_id'), 'roster_entries', ['team_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'PENDING_COUNTER', 'PENDING_LEAGUE_VOTE', 'ACCEPTED', 'EXECUTED', 'REJECTED', 'CANCELLED', 'VETOED', 'COMMISSIONER_EXECUTED', 'COMMISSIONER_CANCELLED', name='trade_status', native_enum=False, length=40), nullable=False),
    sa.Column('proposed_by_team_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_league_id'), 'trades', ['league_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('owner_team_id', sa.Uuid(), nullable=False),
    sa.Column('asset_kind', sa.Enum('DRAFT_PICK', 'FAAB', 'ROSTER_PLAYER', name='asset_kind', native_enum=False, length=32), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('original_team_id', sa.Uuid(), nullable=True),
    sa.Column('faab_amount_minor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('roster_entry_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("\n            (asset_kind = 'draft_pick' AND season_year IS NOT NULL AND round_number IS NOT NULL)\n            OR (asset_kind = 'faab' AND faab_amount_minor IS NOT NULL)\n            OR (asset_kind = 'roster_player' AND roster_entry_id IS NOT NULL)\n            ", name='ck_asset_payload_matches_kind'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['original_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roster_entry_id'], ['roster_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_entry_id')
    )
    op.create_index(op.f('ix_assets_league_id'), 'assets', ['league_id'], unique=False)
    op.create_index(op.f('ix_assets_owner_team_id'), 'assets', ['owner_team_id'], unique=False)
    op.create_table('trade_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('team_order', sa.Integer(), nullable=False),
    sa.CheckConstraint('team_order BETWEEN 1 AND 3', name='ck_trade_participant_order_range'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'team_id', name='uq_trade_participant_team')
    )
    op.create_index(op.f('ix_trade_participants_team_id'), 'trade_participants', ['team_id'], unique=False)
    op.create_index(op.f('ix_trade_participants_trade_id'), 'trade_participants', ['trade_id'], unique=False)
    op.create_table('trade_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trade_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('from_team_id', sa.Uuid(), nullable=False),
    sa.Column('to_team_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_items_asset_id'), 'trade_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_trade_items_trade_id'), 'trade_items', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_items_trade_id'), table_name='trade_items')
    op.drop_index(op.f('ix_trade_items_asset_id'), table_name='trade_items')
    op.drop_table('trade_items')
    op.drop_index(op.f('ix_trade_participants_trade_id'), table_name='trade_participants')
    op.drop_index(op.f('ix_trade_participants_team_id'), table_name='trade_participants')
    op.drop_table('trade_participants')
    op.drop_index(op.f('ix_assets_owner_team_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_league_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_trades_league_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_roster_entries_team_id'), table_name='roster_entries')
    op.drop_index(op.f('ix_roster_entries_player_id'), table_name='roster_entries')
    op.drop_table('roster_entries')
    op.drop_index(op.f('ix_draft_queue_entries_team_id'), table_name='draft_queue_entries')
    op.drop_index(op.f('ix_draft_queue_entries_player_id'), table_name='draft_queue_entries')
    op.drop_table('draft_queue_entries')
    op.drop_index(op.f('ix_teams_user_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_league_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_league_members_user_id'), table_name='league_members')
    op.drop_index(op.f('ix_league_members_league_id'), table_name='league_members')
    op.drop_table('league_members')
    op.drop_index(op.f('ix_leagues_slug'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_players_external_ref'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
